version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MessengerOnTCP
      MYSQL_DATABASE: messenger
    ports:
      - "3306:3306"

volumes:
  db_data: